// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07BrK2-8TKPbSv2IgxlAskHesV3Njj3o',
    appId: '1:534022399824:web:d4197cb0ac2b8f75d9ae55',
    messagingSenderId: '534022399824',
    projectId: 'fir-flutter-codelab-9c2b7',
    authDomain: 'fir-flutter-codelab-9c2b7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-9c2b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDDUYzjZVkgXZH8faRmwx4ttFAkBiHfo',
    appId: '1:534022399824:android:f69216857906e5d0d9ae55',
    messagingSenderId: '534022399824',
    projectId: 'fir-flutter-codelab-9c2b7',
    storageBucket: 'fir-flutter-codelab-9c2b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lepaWwunHV-Ae8E8TDMgo6H4sf5FZqk',
    appId: '1:534022399824:ios:3be00dae5d75f0a6d9ae55',
    messagingSenderId: '534022399824',
    projectId: 'fir-flutter-codelab-9c2b7',
    storageBucket: 'fir-flutter-codelab-9c2b7.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lepaWwunHV-Ae8E8TDMgo6H4sf5FZqk',
    appId: '1:534022399824:ios:3be00dae5d75f0a6d9ae55',
    messagingSenderId: '534022399824',
    projectId: 'fir-flutter-codelab-9c2b7',
    storageBucket: 'fir-flutter-codelab-9c2b7.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA07BrK2-8TKPbSv2IgxlAskHesV3Njj3o',
    appId: '1:534022399824:web:4e32de7f068a0993d9ae55',
    messagingSenderId: '534022399824',
    projectId: 'fir-flutter-codelab-9c2b7',
    authDomain: 'fir-flutter-codelab-9c2b7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-9c2b7.appspot.com',
  );

}